### PR TITLE
Allow setting options via ENV

### PR DESCRIPTION
**Pull request by mkysel**
Add the option to set any option via the ENV.

Prefix all variables with `XMTPD` as best practices dictate.

Remove manual env parsing.

### CODE REVIEW

**Comment by mkysel** [comment]
I will undo the mockery changes...

**Review by neekolas — APPROVED** [review]
Thanks for tackling this. Much tidier this way

**Comment by neekolas** [comment]
> I will undo the mockery changes...

If you run `dev/update-tools` it should put you on the same version of mockery as the go.mod. You may have to `brew uninstall` as well, depending on the order of your PATH

**Comment by mkysel** [comment]
> > I will undo the mockery changes...
> 
> If you run `dev/update-tools` it should put you on the same version of mockery as the go.mod. You may have to `brew uninstall` as well, depending on the order of your PATH

Thanks!

**Pull request merged**
